### ISSUE TITLE
Arrow keys should preventDefault()

### ISSUE THREAD

**Issue by redblobgames** [jarrahtech/RoguelikeTutorial2022#4]
Engine.handleInput receives keydown events and sends them to EventHandler.dispatch. If EventHandler.dispatch handled the key, I think Engine.handleInput should call event.preventDefault(). That way, arrow keys, backspace, space bar, etc. won't cause the page to scroll.

**Comment by cordinc** [comment]
Thanks for pointing this out, its a good idea and I just added the change.
